### ISSUE TITLE
[Question] JWT not in header

### ISSUE THREAD

**Issue by lipkau** [thephpleague/oauth2-server#1012]
Hello.

I am using this package indirectly over Laravel/Passport.
And I am facing a very annoying problem: (amazon) alexa does not adhere to the oauth standard.
they send the accessToken in the body of the request. [See the documentation](https://developer.amazon.com/docs/account-linking/add-account-linking-logic-custom-skill.html#get-token)

From my investigation as a noob, the current package does not offer tools to authenticate a user in this case.

So to my question: what do I do? _(<-- presuming I am right. if not, please give me a like to the fine manual (RTFM) explaining this, which I might have missed)_

**Comment by Sephster** [comment]
I haven't used Alexa but a quick Google search seems to confirm your suspicions, that Amazon is setting the access token in the body rather than the header.

Because the is not valid as per the OAuth 2 spec, we would be unlikely to support this in the core package.

I would advise you extend Passport to support your given case. Sorry I can't be of further help with this.
