### ISSUE TITLE
Token still working after after user deletion

### ISSUE THREAD

**Issue by airguillaume** [thephpleague/oauth2-server#1026]
Hi, 

This is more a question than an issue but; as it is mentioned in the title, if I delete a user, he can still do thing on my service because the token is still valide. How should I manage this case? 

This happened during the development phase. I deleted all my tables, re-run migrations and tried to access a route with a token generated before the reset. The user id is 31, and there is only 30 users; the one which I used the token to access the route isn't there any more.

Any idea, clue on which part I missed? Something to implement to revoke a token or so? Thanks in advance.

P.S : I don't know how to add a tag to flag this as a question ^^.

**Comment by datapp** [comment]
Hi,

it's an expected behaviour. in the moment you create an access token, you have to define the time to life (default: 1 hour). During this hour the token will always be valid. After this period, the app has to refresh the token and your oauth server recognize that the user (and/or the refresh token) isn't valid any more.
oauth is designed for distributed systems, so the resource server don't need a direkt connection to the authorization server, but also don't know immediately when a user was deleted.

**Comment by Sephster** [comment]
You must revoke the access token. It is a bearer token meaning anyone who is in possession of it can access the protected resources the token affords. 

As @datapp mentions, this is by design in the OAuth 2 spec.

I hope this answers your question but if you ah e any further comments please feel free to get in touch

**Comment by Sephster** [comment]
@airguillaume I'm closing this due to a lack of activity but if you have any follow up questions please feel free to get in touch by adding a comment here.
