### ISSUE TITLE
Race condition on key file save in CryptKey because of touch

### ISSUE THREAD

**Issue by velser** [thephpleague/oauth2-server#1062]
Hey fellows.

There is a place, when we can have race condition for key saving. `touch` creates empty file, and if at that point any request will go through file_exists it will return empty file and will not pass through permission checks and other things. Currently i have adapter for CryptKey which do not do any touches.

I would suggest removing touch, as file_put_contents validation is more than enough to check if it can be written. Or do file locking somehow. Is there an important reason to use touch ?

https://github.com/thephpleague/oauth2-server/blob/ad6e191abac400013a9ed6fa71ec6bf576ade872/src/CryptKey.php#L87

How to reproduce:

1. Use string approach `new CryptKey('privatekeyHASH')`
2. Enable multi-request xdebug
3. Put breakpoint on src/CryptKey.php:79 `if (file_exists($keyPath)) {`
4. Make two calls
5. At one call get pass touch function and don't go further
6. On second request step forward so it will return filename because file_exists, tho it's empty
7. On second request u will get an error because of empty file and permissions etc.

It may be rare case, and we generate such files before any input from public, but still file writing can lag sometimes if you don't prepare everything before any requests can come through and race condition may happen, as it's easy to reproduce manually.

For example from my perspective it happened sometimes with parallel functional tests

**Comment by Sephster** [comment]
Thanks for reporting this @velser - it looks to be a legacy issue. Originally, the code used to check if the file exists and if it could touch. If everything passed, it would write the file.

At some point around two years ago, we put the file writing in an if statement  to check if the file had actually been written. In all honesty, I can no longer see the reason for the touch statement, because as you say, we will either write the file or we won't. 

I will flag this as a bug to fix in future. Thank you
