### ISSUE TITLE
Change UserRepository users table

### ISSUE THREAD

**Issue by diego-sorribas** [thephpleague/oauth2-server#1091]
Hi ! It is possible to change where the UserRepository check the users credentials ? For example if I have already a users table how I can implement oauth2-server check my users table instead the oauth_users? 

In bshaffer oauth2 server you can pass config to the storage.

**Comment by Sephster** [comment]
The package doesn't specify which tables (or even which storage mechanism) you use. You are free to implement this however you want. All as you need to do is create a UserRepository that implements the UserRepositoryInterface.

That interface has a function called `getUserEntityByUserCredentials`. You can implement this function so that it checks your existing table.

As long as you make it return a UserEntity object that implements the UserEntityInterface, you should be good to go.

I hope I've understood your question correctly, but if not, please feel free to come back with further comments and I will try my best to answer your questions. Thanks
