### ISSUE TITLE
Support adding `issuer` claim to the access token JWT

### ISSUE THREAD

**Issue by Pchelolo** [thephpleague/oauth2-server#1137]
The JWT [iss](https://tools.ietf.org/html/rfc7519#section-4.1.1) claim is a registered claim name for the JWT standard. Some validator implementations, most notably [envoyproxy](https://www.envoyproxy.io) require the issuer claim to be set in various circumstances, however there's no way right now to specify the claim in the access token emitted by the library.

**Comment by Sephster** [comment]
Hi @Pchelolo. Thanks for your PR. The _ISS_ claim is not required as per the JWT spec so the JWTs issued by the server are valid.

I believe the reason we haven't included the claim initially is because our access token entities are converted to JWTs when they are issued using the AccessTokenTrait. 

If you want to add an issuer, you could replace the AccessTokenTrait's `convertToJWT` call with code that sets the issuer you wish. For this reason, I don't think we will progress with this PR at this time but thank you very much for your efforts here.

I hope this resolves your issue but please do get back in touch if you have further problems or comments. Many thanks.

**Comment by tgr** [comment]
@Sephster wouldn't [RFC 9068](https://datatracker.ietf.org/doc/html/rfc9068) be the relevant spec here? That [does make `iss` required](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2).
