### ISSUE TITLE
Error: invalid client and client authentication failed with status code 401 Unauthorized when requesting access_token

### ISSUE THREAD

**Issue by alessandrog22** [thephpleague/oauth2-server#1234]
I am using this library and the client one for a project and, after the sign in/sign up and the authorization of the scopes, following the Auth Code Grant flow, I have to request an access_token that lets the user call the apis. But after some debug I reach this error from the response. I hope someone can help me.
![Senzanome](https://user-images.githubusercontent.com/37110712/120814814-8470b800-c54f-11eb-9ac2-376c665d4a49.png)

**Comment by Sephster** [comment]
Apologies for the delay in replying. With the auth code grant, usually this error is thrown because your redirect URI does not match any of the redirect URIs the client was registered with. If this is not the case, the client credentials provided will be failing. You should check both of these in your request to determine which scenario might be causing this.

Hope this helps and good luck with the fix!
