### ISSUE TITLE
Class "League\Uri\UriString" not found

### ISSUE THREAD

**Issue by jmpecx** [thephpleague/oauth2-server#1371]
```
Class "League\Uri\UriString" not found
```

![image](https://github.com/thephpleague/oauth2-server/assets/131391075/f1c75583-66ce-484f-b798-2282f1829780)

8.5.3 works find.

Anyone else had this problem?

**Comment by parallels999** [comment]
@jmpecx seems like a bug on League/Uri, not from here

**Comment by Sephster** [comment]
The URI String class is in the [uri interfaces](https://github.com/thephpleague/uri-interfaces) package which is a dependency of v7 of league/uri. 

I'm assuming you don't have this package in your vendor directory. Is this the case?

**Comment by parallels999** [comment]
> If there is no feedback from others, it may be due to issues with my environment.

That has happened to me, sometimes, I have not known how to solve it, what I have done is delete the entire vendor manually and composer update

If you find the solution, let me know, so I can have that knowledge. 👀👀

**Comment by Sephster** [comment]
Sorry @jmpecx, just to confirm, was v7 in your vendor dir or did it stay on an earlier version?

You can run `composer why-not league/uri 7.0` to find out why it didn't install if this is the case.

Let me know how you get on

**Comment by cweiske** [comment]
I have the same problem on a Drupal 9.5 installation
- `league/uri-interfaces` 7.0.0-beta.2 
- because of `league/uri`: `league/uri 7.0.0 requires league/uri-interfaces (^7.0)`
- because of `drupal/simple_oauth` 5.2.5

`uri-interfaces` 7.0.0-beta.2 does not have the UriString class. I can't update to uri-interfaces 7.0.0 or higher, because
- `uri-interfaces` 7.0.0 stable requires `psr/http-message (^1.1 || ^2.0)`
- `drupal/core-recommended` 9.5.11 requires `psr/http-message` ~1.0.1, thus can't update to 1.1

So in my case I'm stuck with `psr/http-message` 1.0, and thus stuck with `league/uri-interfaces` 7.0.0-beta.2 which misses the `UriString` class.

**Comment by cweiske** [comment]
My `composer.json` has a `"minimum-stability": "dev"` for reasons I don't have control over (subdependencies only available as beta and dev stability).

My workaround is to mark the beta versions of uri-interfaces as conflicting in `composer.json`:
```
    "conflict": {
        "league/uri-interfaces": ">=7.0.0beta.1 <=7.0.0-beta.2"
    },
```
