### ISSUE TITLE
Support league/event v3

### ISSUE THREAD

**Issue by shyim** [thephpleague/oauth2-server#1387]
Allow installation of league/event v3

**Comment by Sephster** [comment]
This is being worked on and should be released in a few weeks 👍

**Comment by TomHAnderson** [comment]
I just had to revert my library https://github.com/API-Skeletons/doctrine-orm-graphql because I used version 3 of the league event manager.  As it is impossible to install this server alongside my library because this server does not support version 3 of the league event manager, I now have two versions of my library.

I consider version 3 to be excellent and I want to continue supporting it exclusively.  The closed message by @Sephster of "not planned" conflicts with the comment on the same day indicating a future release with version 3 support.  I know this issue has been closed but because it was never resolved can this be reopened?

**Comment by Sephster** [comment]
It is in v9 RC1 which we are putting the finishing touches to now.
