### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by vvllaadd** [thephpleague/oauth2-server#296]
Hi Alex,

First, thank you for your work. It looks like a greatly designed library which takes consideration of many of the security shortcomings of the OAuth2.

Here's some feedback:

The implementation of the library in my project, although not very difficult, took a big chunk of my time, mostly because of the use of "Illuminate\Database\Capsule" in the example. It might be a great library and you might have extensive experience for it, but taken that the example should focus on the functionality of this library and not others, it badly needs to be reimplemented with a basic PHP SQL extension which clearly shows the SQL queries, and which everybody is so familiar with. For somebody new to Capsule, it takes quite a bit of time to translate the functionality to plain SQL or some other library than Capsule. There could also be a plain SQL dump file for initializing the database structure quicker, instead of translating the programmatic way. This might lead to less mistakes, as if you get any of the SQL queries wrong, it's done and it take quite bit of troubleshooting to find the problem.

Because I don't like the fact that the auth codes and other tokens repeat themselves across multiple tables, and in my project's database all tables have a column called id, which is incremental and unique and used for referencing records from other tables, it took me a bit to adjust the whole library to it. I think it's a better practice to keep the tokens only in their own tables. Let me know if you want me to describe what changes I made in the library for this.

P.S. 50% of all PHP websites still use PHP 5.3. You are missing out on a lot of users by keeping higher requirements for the library.

Best regards,

Vlad

**Comment by alexbilbie** [comment]
Hi Vlad,

Thank you for your email.

Regarding the examples, the intention was to eventually provide multiple versions (hence why the current examples are in a folder called `relational` - i.e. relational database).

I used Capsule simply for it's query builder and time. The library is purposely agnostic of the backend, as some developers aren't using relational databases at all, whereas for me I use a combination of MySQL + flat file arrays depending on what I want to do.

I'm not sure what you mean by tokens repeating themselves - they should all be unique. The fact that you've been able to implement your structure as you have shows how flexible the library is so that it can be integrated as developers see fit into existing and new applications.

Regarding your comment about PHP 5.3 - it's irresponsible to be trying to do security related activities with an out of date version of PHP which itself doesn't have security fixes anymore.

Alex

**Comment by vvllaadd** [comment]
Sorry, I should have been a bit more clear about the tokens repeating themselves. They are unique, it's just that the long random strings are being used directly, instead of a small integer to reference them across tables. In an environment with many users, many third-party apps, the database can get quite big.

> it's irresponsible to be trying to do security related activities with an out of date version of PHP which itself doesn't have security fixes anymore. <

Based on this logic you should develop only for PHP 5.6 and when 5.7 is out, instantly drop any backwards compatibility.
Unfortunately it needs to be done for business and practical reasons and it's a pity that exceptional developers fail to understand the need. This is because developers are still focused on creating code instead of creating products.
As a perfect analogy, 18% of all computers on this planet still run Windows XP. It is an out of date operating system which doesn't have security fixes anymore. From the development perspective, it's easy to dump support for them - it takes less work. But from a business and user perspective it is just not smart to ignore so many people and potential customers.
