### ISSUE TITLE
Never expire access tokens?

### ISSUE THREAD

**Issue by fabianpimminger** [thephpleague/oauth2-server#334]
Is it possible to issue tokens that will never expire? Like setting the TTL to -1?

**Comment by filfat** [comment]
+1

**Comment by robertpitt** [comment]
Access Token expiry is an integral part of a Secure Oauth infrastructure, by adding such a feature would reduce security if used.

Can you give a good reason why this would be beneficial apart from reducing the development work need to implement a rotating access token mechanism on the client application.

-1

**Comment by filfat** [comment]
@robertpitt It would be extremely useful in development & certain unit test, ofc I would never use it in production. :)

**Comment by robertpitt** [comment]
In development, I just set your TTL to `52 * 604800`, I'm sure 1 year will suffice for your need's :/

**Comment by alexbilbie** [comment]
As @robertpitt suggested when your storage class looks for an access token simply don't validate the access token's expiry. There's no need for the library to implement any additional logic.

But do consider his advice about security.

**Comment by m4tthumphrey** [comment]
I feel there is definitely a use case for this. GitHub for example, offer Personal Access Tokens which never expire. This is not something you can easily implement into the client either because the exception that is thrown for an expired token is the same as when no token exists. I have looked into building into the storage interfaces but there is no easy when to do this based on a specific client; you can only do it across all clients. 

With the introduction of factories (#307) for creating entities this should be much easier to implement however.
