### ISSUE TITLE
Decouple domain model/logic and external interfaces 

### ISSUE THREAD

**Issue by mbrevda** [thephpleague/oauth2-server#336]
Currently, the domain and the "server" are tightly coupled. In the name of SRP, and following a pattern like [ADR](https://github.com/pmjones/adr), it might be beneficial to decouple the domain/logic parts of the code and the other parts.

Aside for better coding structure, this would also allow users of other external interfaces (i.e. a router from a framework like Aura or Laravel) to reuse said interfaces, which the rest of their app already uses. This would also minimize the code this project implements for dealing with external interfaces (i.e. reading a header, etc), and instead rely on the data being passed in.

Finally, if the intent is offer a complete package, this can be offered separately, pulling in the domain as a dependency.

**Comment by alexbilbie** [comment]
Version 5 of the app (currently in dev) has already started to address some of these concerns and has a much better structure.

The next step would be to use value objects instead of working directly with Symfony's request object to allow for easier interoperability with other implementations.

So yes I agree with your points and they should be addressed in v5.

**Comment by mbrevda** [comment]
I actually need to implement an auth server a. What is the eta for v5? Can
I do anything to help get it released in the near future?

**Comment by alexbilbie** [comment]
I think I've now addressed these problems in V5
