### ISSUE TITLE
Add expire_time to newly created token

### ISSUE THREAD

**Issue by lukasoppermann** [thephpleague/oauth2-server#373]
Hey,
when a token is created using `issueAccessToken` it returns `expires_in = 3600` or whatever you set.
I think it would be very useful to get an `expire_time` back. 

My suggestion would be to add this field to the returned data.

**Comment by dekker-m** [comment]
Why do you think this is useful?

The reason oauth defines`expires_in` instead of an `expire_time` is to account for servers configured with different times. It can happen my client has it's time set half an hour earlier. If you would return `expire_time` instead of `expires_in`, my client would still think the access token is valid, while it has actually expired half an hour ago. If my client would use `expires_in` he can adjust this time to his own local time and determine the exact time the access token will expire. If you do this, there is no point in providing the `expire_time` in the response.

Or is there another reason why you want to add this response parameter?

**Comment by lukasoppermann** [comment]
Hmm, this is of course a valid reason as well. I was coming from the other side. If I create a token and the server returns it, than I save it to the database, there will be some time passing between my timestamp and the servers timestamp, so in the end, there will be a timespan where my code thinks the token is valid, but actually it is not valid.

**Comment by dekker-m** [comment]
I understand what you are saying, but under normal circumstances with a low network latency this should not cause too much trouble. I normally advise clients to refresh the access tokens a few seconds before it really expires to prevent this problem.

**Comment by lukasoppermann** [comment]
Hmm, maybe that is enough. I guess this could be done. Thanks anyway.

**Comment by alexbilbie** [comment]
The OAuth spec says that you can add your own arbitrary key pairs in the response which you can hardcore your own clients to use and other clients will ignore but as @dekker-m said, latency and time sync issues make it a tricky problem to solve
