### ISSUE TITLE
Return the refresh token expiration in the response

### ISSUE THREAD

**Issue by gnrcampos** [thephpleague/oauth2-server#394]
I'm not too sure if I missed some concept but is there a reason why you don't get the "expire_in" for the refresh token? After messing a little bit with the code I noticed that it takes only a few lines to achieve it, as shown below:

TokenType/Bearer.php
```
public function generateResponse()
    {
        $return = [
            'access_token'  =>  $this->getParam('access_token'),
            'token_type'    =>  'Bearer',
            'expires_in'    =>  $this->getParam('expires_in'),
        ];

        if (!is_null($this->getParam('refresh_token'))) {
            $return['refresh_token'] = $this->getParam('refresh_token');
            $return['refresh_token_expires_in'] = $this->getParam('refresh_token_expires_in');
        }

        return $return;
    }
```
Grants/PasswordGrant.php -> For example
```
    public function completeFlow()
    {
        ...
            // Associate a refresh token if set
            if ($this->server->hasGrantType('refresh_token')) {
                $refreshToken = new RefreshTokenEntity($this->server);
                $refreshToken->setId(SecureKey::generate());

                $v_RefreshTTL = $this->server->getGrantType('refresh_token')->getRefreshTokenTTL();
                $refreshToken->setExpireTime($v_RefreshTTL + time());
                $this->server->getTokenType()->setParam('refresh_token', $refreshToken->getId());
                $this->server->getTokenType()->setParam('refresh_token_expires_in', $v_RefreshTTL);
           }
        ...
```

**Comment by starJammer** [comment]
I think that this was done this way because the OAuth2 spec doesn't explicitly say that refresh tokens expire.

**Comment by gnrcampos** [comment]
@starJammer In this case, how do I set a never expiring refresh token? I searched it in the documentation, here and even went through the code, but it seems that if I do what I think would be the most intuitive thing, setting the expiration time to zero or a negative value, this method
```
public function isExpired()
{
    return ((time() - $this->expireTime) > 0);
}
```
would just return false.

**Comment by starJammer** [comment]
@gnrcampos , the best way I found to do this was to "fudge" my `RefreshTokenStorage` implementation. Whenever the refresh token is fetched via the get method I set the expire time in the refresh token entity to one year from `now `. In this way the `isExpired` method will always return true on the entity. 

This creates a problem because you might want to expire a refresh token for some reason. What you can do is create a Boolean column on the refresh token table `is_expired`. If it is true your storage implementation will set the expiration time for each token it fetches to be a year from `now` and if it is falsi it'll set the expiration time to some in the past.

Does that make sense?

**Comment by gnrcampos** [comment]
@starJammer yes it does make sense, thank you very much. I'm gonna go over the possibilities but so far this one seems to be the best.

**Comment by alexbilbie** [comment]
I will improve the documentation to make this clearer
