### ISSUE TITLE
How to force all tokens expire if user change password?

### ISSUE THREAD

**Issue by richat** [thephpleague/oauth2-server#566]
Dear Sir,

I have logged-in with username and password, then it will give me the token back that is expired with in an hour.

How can we force this token expire before this in case user change his/her password?

Thanks

**Comment by alexbilbie** [comment]
In direct answer to your question when the user changes their password you should just expire all of their access tokens in your database so that when an access token is used this method https://github.com/thephpleague/oauth2-server/blob/master/src/Repositories/AccessTokenRepositoryInterface.php#L40-L47 returns `true`.

I would strongly question though whether or not this is the right thing to do in terms of user experience. If I changed my password on Twitter and I had to re-sign into every Twitter app on my computer, tablet and phone I'd be really annoyed.

OAuth is about authorization not about authentication - i.e. the user has given their permission for a client to access data on their behalf. The fact that their password has changed should not mean that their permission to clients has changed

**Comment by richat** [comment]
@alexbilbie , what is your recommendation when user change password?

**Comment by alexbilbie** [comment]
If the user has changed their password of their own free-will then just change their password. Leave their access tokens alone.

If the user is resetting their password because their account has been compromised then it may be a good idea to revoke their access tokens.

**Comment by richat** [comment]
This is great idea. Thanks you very much!
But how to revoke their access tokens (good way)?

**Comment by alexbilbie** [comment]
If you are persisting the tokens in a database of some sort then you can invalidate them in there, so that when a token is used [the method here](https://github.com/thephpleague/oauth2-server/blob/master/src/Repositories/AccessTokenRepositoryInterface.php#L40-L47) returns `true` to indicate that the token is revoked.

**Comment by richat** [comment]
Hi sir,
I am sorry, I don't know how to use this method in my controller.
