### ISSUE TITLE
Apart OAuth2 server - Validate on other API's

### ISSUE THREAD

**Issue by bobmulder** [thephpleague/oauth2-server#579]
Hey all,

For a project I am planning to build 3 API's, and all of them are going to use OAuth2.
I've read a lot about it, and talked a lot about it and I am starting to understand it....

I decided to build one extra API, which is the OAuth2 API. I guess I should use this awesome library for that.

But, what about securing my 3 other API's? I would love to use the middleware (https://oauth2.thephpleague.com/resource-server/securing-your-api/), but I can't figure out how the middleware should validate it via the OAuth2 API. Any hints? 

Thank you very much!

Greetz,

Bob

**Comment by alexbilbie** [comment]
Hi Bob,

So your auth server (i.e. the implementation of this library) will issue access tokens (specifically JWTs signed using the auth servers private key).

The API clients then use the access tokens as authorisation when calling your other APIs.

Each of those APIs implement the resource server middleware that you linked to in your question. When the access token in the request is parsed by the middleware a few things will happen:

1. The middleware will check the access token is signed by the Auth server's public key
2. The middleware will then check the access token hasn't expired
3. Finally the `isAccessTokenRevoked` method on [`AccessTokenRepositoryInterface`](https://oauth2.thephpleague.com/access-token-repository-interface/) (that was passed into the `ResourceServer` class when you initialised it) will be called to verify the access token hasn't been revoked since it was issued.

If the access token is valid the following attributes will be set on the HTTP request that was passed into the middleware:

* `oauth_access_token_id` - the access token identifier
* `oauth_client_id` - the client identifier
* `oauth_user_id` - the user identifier represented by the access token
* `oauth_scopes` - an array of string scope identifiers

If the authorization is invalid an instance of `OAuthServerException::accessDenied` will be thrown.

Does that answer your question?

**Comment by bobmulder** [comment]
Hi Alex,

Thank you for taking time to answer my strugge ;)

> So your auth server (i.e. the implementation of this library) will issue access tokens (specifically JWTs signed using the auth servers private key).

> The API clients then use the access tokens as authorisation when calling your other APIs.

Completely agree, I already got that...

> Each of those APIs implement the resource server middleware that you linked to in your question. When the access token in the request is parsed by the middleware a few things will happen:

> - The middleware will check the access token is signed by the Auth server's public key
- The middleware will then check the access token hasn't expired
- Finally the isAccessTokenRevoked method on AccessTokenRepositoryInterface (that was passed into the ResourceServer class when you initialised it) will be called to verify the access token hasn't been revoked since it was issued.

I don't get this completely. To be clear, the Auth server is not integrated IN my 3 API's. Lets say I have the following list:

- auth.myapi.com
- api1.myapi.com
- api2.myapi.com
- api3.myapi.com

The cliënt should first get his access token via `auth.myapi.com`, and then could access all of the 3 API's with that access token. The 3 API's should check with scopes if he can access those endpoints, but thats my business ;)

You say that API1, API2 and API3 will implement the Resource Server middleware, but that means that they need to load this library as well in the 3 API's? And they need access to the samen database as the Auth server as well? 

Again, thanks for your help!

Greetz,

Bob

**Comment by alexbilbie** [comment]
> You say that API1, API2 and API3 will implement the Resource Server middleware, but that means that they need to load this library as well in the 3 API's?

Currently yes; but it isn't that big... 😄 

>  And they need access to the same database as the Auth server as well?

Not necessarily; you could set up a private API on your auth server that can be called in the `isAccessTokenRevoked` method to verify this. Alternatively you could always return `false` (i.e. the access token has not been revoked) if you don't anticipate needing to revoke access tokens.

There is an RFC called ["OAuth 2.0 Token Introspection"](https://tools.ietf.org/html/rfc7662) which "allows a resource server to query an OAuth 2.0 authorization server to determine the active state of an OAuth 2.0 token and to determine meta-information about this token", but I've not yet had a chance to evaluate it and implement it in this library.

**Comment by bobmulder** [comment]
Thank you very much for making this clear Alex! I will try to work something out.

If I have any questions, is opening a new issue the right way, or can we set something up with [Gitter](https://gitter.im)?

**Comment by alexbilbie** [comment]
Can you open a Github issue please; it gives me something to link to if people ask similar questions
