### ISSUE TITLE
Discussion: the purpose of TokenInterface::isExpired()

### ISSUE THREAD

**Issue by zerkms** [thephpleague/oauth2-server#598]
What is the purpose of the `League\OAuth2\Server\Entities\TokenInterface::isExpired()` method if it's not used anywhere?

**Comment by alexbilbie** [comment]
As this is handle by the underlying JWT library it can be removed

**Comment by zerkms** [comment]
@alexbilbie and JWT library would be my next question - I understand it is probably too late, but what do you think about design that allows to optionally opt-in into using JWT?

We are using persistence storage for managing tokens so having extra requirement of pub/private keys to manage is just an extra work to do.

**Comment by alexbilbie** [comment]
I switched to JWTs in v5 of the library because it solves a few implementation problems. Because JWTs are signed self-contained payloads they can be used in distributed architectures where each resource server may not have access to the underlying token persistence layer - likewise there might not even be permanent persistance and instead a revocation persistence layer instead (i.e. only store revoked tokens instead of all tokens).

The aim of this library is to provide a solid foundation for building an OAuth server out of the box and having built tens of OAuth servers now I think moving to JWTs as the default implementation is still a good idea.

If you implement the classes `League\OAuth2\Server\AuthorizationValidators\AuthorizationValidatorInterface` and `League\OAuth2\Server\ResponseTypes\ResponseTypeInterface` you'll be able to by-pass the JWT stuff and work with more traditional bearer tokens; I realise however that you'll still need to bind the public and private keys for now but as I don't believe they will actually be used outside the JWT stuff it shouldn't matter if these are dummy files. 

I do appreciate your concern though and I think I'm going to release v6 at some point this summer (and maintain it side by side with v5) to address a few small API design issues such as this to make the library even more flexible.

**Comment by zerkms** [comment]
Good, thanks :-)
