### ISSUE TITLE
while(array_shift()) over grant types, sounds weird

### ISSUE THREAD

**Issue by pounard** [thephpleague/oauth2-server#617]
While reading this piece of code, in the AuthorizationServer class (which can be see multiple times):

```php
        while ($authRequest === null && $grantType = array_shift($enabledGrantTypes)) {
            /** @var \League\OAuth2\Server\Grant\GrantTypeInterface $grantType */
            if ($grantType->canRespondToAuthorizationRequest($request)) {
                $authRequest = $grantType->validateAuthorizationRequest($request);

                return $authRequest;
            }
        }
```

I can't get out of my mind this question: why would you use array_shift() ? It makes the object mutable and it looses the grants implementation, it makes it non-reusable.

In real life it doesn't seem that bad since we are supposed to actually use it once, but it definitely doesn't make any sense, or I am wrong ?

**Comment by alexbilbie** [comment]
As you said, the object isn't re-used afterwards.

If you can suggest some reasons why an alternative implementation would be preferable because the information is needed later on I'm open to suggestions 😄

**Comment by pounard** [comment]
Hum, it's only a matter of pure brain logic, whereas your object works considering that PHP spawns and dies at the end of the request, it's OK, but if you want to use it with, let's say, something like PHP-PM (using ReactPHP) then it's not gonna work. I think that the various enabled grants are software configuration (in my very own case dependency injection container configuration) - and should probably not be mutable this way, it shows a design flaw.

It was weird the first time I read the code because I didn't know if it was a real feature to remove the grants from the authorization server or not, I think that code understanding and readability should win over other considerations especially with something as complex as OAuth2.

Another possible implementation is a simple foreach() in the end :)

**Comment by alexbilbie** [comment]
Please feel free to submit a patch :)


On 13 July 2016 at 10:49:14, Pierre (notifications@github.com) wrote:

Hum, it's only a matter of pure brain logic, whereas your object works
considering that PHP spawns and dies at the end of the request, it's OK,
but if you want to use it with, let's say, something like PHP-PM (using
ReactPHP) then it's not gonna work. I think that the various enabled grants
are software configuration (in my very own case dependency injection
container configuration) - and should probably not be mutable this way, it
shows a design flaw.

It was weird the first time I read the code because I didn't know if it was
a real feature to remove the grants from the authorization server or not, I
think that code understanding and readability should win over other
considerations especially with something as complex as OAuth2.

Another possible implementation is a simple foreach() in the end :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/oauth2-server/issues/617#issuecomment-232309169>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAEwpziHYkbitCcP8B_aC2DcLCodk0yUks5qVLSZgaJpZM4JKiZ3>
.

**Comment by pounard** [comment]
Done https://github.com/thephpleague/oauth2-server/pull/621
