### ISSUE TITLE
It's pretty difficult to avoid JWT

### ISSUE THREAD

**Issue by bpicolo** [thephpleague/oauth2-server#630]
Figured I'd raise this as an issue because it was a bit of a frustration to make use of the library.

The library isn't particularly forgiving to not wanting to use JWT. I may somehow be mistaken, but baseline OAuth2 shouldn't require signing keys of any sort. To avoid having to generate signing keys for oauth2, we had to do some pretty nasty inheritance/overrides for AuthorizationServer, ResourceServer and the BearerTokenValidator. 

It would be cool if the library supported, built in, a good way to not care about signing keys for JWT and just do oauth2.

**Comment by alexbilbie** [comment]
I switched to JWTs in v5 of the library because it solves a few implementation problems. Because JWTs are signed self-contained payloads they can be used in distributed architectures where each resource server may not have access to the underlying token persistence layer - likewise there might not even be permanent persistance and instead a revocation persistence layer instead (i.e. only store revoked tokens instead of all tokens).

The aim of this library is to provide a solid foundation for building an OAuth server out of the box and having built tens of OAuth servers now I think moving to JWTs as the default implementation is still a good idea.

If you implement the classes `League\OAuth2\Server\AuthorizationValidators\AuthorizationValidatorInterface` and `League\OAuth2\Server\ResponseTypes\ResponseTypeInterface` you'll be able to by-pass the JWT stuff and work with more traditional bearer tokens; I realise however that you'll still need to bind the public and private keys for now but as I don't believe they will actually be used outside the JWT stuff it shouldn't matter if these are dummy files.

I do appreciate your concern though and I think I'm going to release v6 at some point this summer (and maintain it side by side with v5) to address a few small API design issues such as this to make the library even more flexible.

**Comment by xiehan** [comment]
@alexbilbie Just want to point out that if your server is not able to handle this kind of encryption of any payloads at all (we're putting it on our backlog but for right now it's just kind of a bridge too far for us, attempting to upgrade from V4 without breaking changes for clients in a very limited amount of time), you also need to subclass `AuthCodeGrant` and `ImplicitGrant` and `RefreshTokenGrant`, because they encrypt/decrypt other payloads. That's quite a lot of subclassing required to avoid the encryption...

**Comment by bobmulder** [comment]
Sorry for interrupting, but what's wrong with the fact all access tokens would become invalid on the new version? Everybody needs to authorize again to gain a new access token... Thats all... Right?

**Comment by xiehan** [comment]
@bobmulder That's essentially asking us to log everybody out and force them to log in again, and that's not an option for us. We're in the middle of a huge marketing/growth campaign, so anything that might adversely affect our retention numbers is going to be deemed unacceptable. An estimated 5% of users will never log back in again if we log them out, and even for those who do, we'll get complaints as well as a slew of negative reviews in the App Store. We're never going to get management sign-off on that, ever.

And that's just for our in-house apps. We have a bunch of third-party clients with whom we've got legal contracts in place that prevent us from making breaking changes to the API, at least without 3-months' notice, and I'm pretty sure logging everybody out would fall under that category. So this wouldn't fly with them, either.

**Comment by bpicolo** [comment]
For clarity, we did eventually rewrite a bunch of class logic to make this work. It does also require rewriting parts of the relevant grants, it is true, though we had other reasons to do that for integrating with legacy code as well. Definitely possible though.

**Comment by bobmulder** [comment]
You're right @xiehan, Good luck!
