### ISSUE TITLE
Token validators

### ISSUE THREAD

**Issue by chervand** [thephpleague/oauth2-server#660]
Hi, are you planing to provide:

- any other built-in authorization validators or make existing BearerTokenValidator's signing algorithm  configurable?
- support for non-JWT tokens?
- support for non-Bearer tokens (i.e. MAC)?

Thank you.

**Comment by alexbilbie** [comment]
In order of your questions:

* Do you have any examples of what you'd like to see as alternatives?
* At this point no - what the next version (alpha coming shortly) will support is JWT tokens that are signed with a HMAC key instead of RSA keys meaning you don't need to generate a public and private key
* The library used to have support for MAC tokens but the draft specification changed quite significantly so I dropped it for the time being because noone was using it.

The entire library is designed to be extensible by conforming to various interfaces - if you've suggestions for new built-in functionality I'm always open to new ideas

**Comment by chervand** [comment]
- I started to explore your library recently and i'm not sure whether it can break anything or not, but what about passing a Signer class to the constructor

```php
$server = new ResourceServer(
    $accessTokenRepository,
    $publicKey,
    new BearerTokenValidator($accessTokenRepository, Lcobucci\JWT\Signer\Hmac\Sha256::class)
);
```

- Are you going to completely remove RSA keys or HMAC is going to be a default option? Anyway, looking forward.
- I need it for my current project :), so i'm going to try to somehow extend your lib for that case.

Thank you your quick response.

**Comment by alexbilbie** [comment]
Both RSA keys and HMAC will be available - if your authorization server and resource server are the same codebase use HMAC, if they're separate codebases then RSA is a better option.

Your code change isn't necessary because the an `AuthorizationValidatorInterface` is already passed in which validates tokens

**Comment by chervand** [comment]
Ok, should i close the issue?
