### ISSUE TITLE
[SECURITY CONCERN/FLAW/BUG] An API Authorization token with changed last character is still allowed authorization.

### ISSUE THREAD

**Issue by jeremykenedy** [thephpleague/oauth2-server#702]
Hi, I am investigating a security issue with your package used in Laravel Passport and was advised to reach out to you.

I think your work is awesome and I appreciate the great work!

Testing from Postman....

Certain invalid tokens allow access when they probably shouldn't.
When the last char of the token is incremented to its next (ASCII) value the endpoint is still allowed access but used to return a 401 as expected.

For example, incrementing the last char 'Q' to 'R' (or next 3 letters proceeding capitalized) in a given token and then accessing an endpoint, the request succeeds when it shouldn't.

The seems like a very big security issue.

Original issue report can be found at: https://github.com/laravel/passport/issues/257

**Comment by alexbilbie** [comment]
First of all this is really irresponsible disclosure. Both this repository and the Laravel repositories have got guidance on how to report security vulnerabilities.

Second this isn't an issue due to the way base64 character encoding works. Depending on the encoded data you may be able to change a few characters at the end of the token without affecting modifying the encoded data.

So this isn't a security issue.

**Comment by jeremykenedy** [comment]
I removed the title and comment per your comment. You are correct, I did not read the readme in full before posting this. However, you are incorrect about the Passport stating a guideline and I was following one of their contributor recommendations to reach out to you. 

Moving past the miss understanding, can this still be checked out?

**Comment by alexbilbie** [comment]
As I said before this isn't an issue.

When you base64 data (for example the JWTs created via this library) the
encoding process may add padding to the final output. Because these extra
ASCII characters are just padding you can modify them to other characters
without affecting the data that has been encoded.

The JWT validation doesn't compare the base64 encoded data, it compares the
decoded data.

**Comment by jeremykenedy** [comment]
Okay, thank you for taking the time to explain. I appreciate your time.
