### ISSUE TITLE
Login dialog popup if wrong client credential used

### ISSUE THREAD

**Issue by i906** [thephpleague/oauth2-server#704]
I am using Laravel Passport, when an invalid client credential is used (example.com/oauth/authorize) and after user successfully logged in (example.com/login), the following popup appears.

![screen shot 2017-02-09 at 8 20 41 pm](https://cloud.githubusercontent.com/assets/866735/22783111/590c1a76-ef05-11e6-86ec-1d33d9044169.png)

From what I understood from the comments at `getHttpHeaders` in OAuthServerException [(commit)](https://github.com/thephpleague/oauth2-server/commit/251190d8282cda89a37f688e172776153df811f6#diff-f213674348aa9b10cba7938f279f9c84), the WWW-Authenticate response header is added when the client authenticates via the Authorization request header.

However, the client does not send the Authorization header. Shouldn't the WWW-Authenticate header is omitted in this case?

**Comment by alexbilbie** [comment]
Nope, the OAuth standard says throw a WWW-Authenticate header.

The client can use it's id and secret as the username and password.

**Comment by i906** [comment]
I did try entering the correct client id and secret into the dialog, but it does not seem to work. I encountered this dialog when I used a different redirect_uri than the one registered.

**Comment by Sephster** [comment]
Hi @i906. Apologies for the delay in picking this up again. Did you manage to resolve your issue? Let us know if we can be of any assistance

**Comment by i906** [comment]
Hi @Sephster 

I thought that authentication dialog was confusing the users so I removed the `WWW-Authenticate` header to prevent the dialog from showing and return a 403 instead.

```php
if ($response instanceof Zend\Diactoros\Response) {
    if (!$request->hasHeader('Authorization')) {
        $response = $response->withoutHeader('www-authenticate');
    }
}
```

**Comment by Sephster** [comment]
Hi @i906 - thanks for replying. Glad you sorted your issue. I believe as Alex stated, that the `www-authenticate` header should be sent as stated in the OAuth2 RFC so I would advise against this.

Since you've resolved your problem and there doesn't appear to be any immediate bug with the server where it is not conforming to the spec, I will close this issue. Thanks very much for taking the time to write back.

If you believe there is still an issue, please feel free to comment back and we will take a further look.
