### ISSUE TITLE
Why does the same access_token is being returned all the time?

### ISSUE THREAD

**Issue by jilvin** [thephpleague/oauth2-server#743]
It seems that same access_token is being returned all the time for a client in Client Credentials Grant mode. Is this an issue or a feature of OAUTH2 standard?

**Comment by Sephster** [comment]
Hi @jilvin - sorry for the delayed response. I've tested this and I don't believe the system is providing the same access token every time. When requesting an access token I received the following results:

```
{"token_type":"Bearer","expires_in":3600,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRkNDUyYmMyNjFlZWY4MzRiYjk3NTAyYWRjMmNjZDI5MGQwMjlhYjYxZTIwZGFiZTRmNzkxMGY1MzA5ZmVmZjg5NjdmNTI5NDJiM2ZhZDUyIn0.eyJhdWQiOiJteWF3ZXNvbWVhcHAiLCJqdGkiOiJkZDQ1MmJjMjYxZWVmODM0YmI5NzUwMmFkYzJjY2QyOTBkMDI5YWI2MWUyMGRhYmU0Zjc5MTBmNTMwOWZlZmY4OTY3ZjUyOTQyYjNmYWQ1MiIsImlhdCI6MTUyMjcwNDc0OCwibmJmIjoxNTIyNzA0NzQ4LCJleHAiOjE1MjI3MDgzNDgsInN1YiI6IiIsInNjb3BlcyI6WyJiYXNpYyIsImVtYWlsIl19.SAUpldSZq4ZHqqwpgrylkqJ8jwiOPZ18rLkvzro-2AQKHvHRzvr6qX-RpK5-x3uAeOVlhM4qFfg3gFtsqfk39hsX0QFH8BiOfxPWIjco4cwW4b9PlzwKWfZr4Vq__qYt1IZB5Ramk0g7MUKnLiw7jHfOWl7zj6croibfhfo3xPg33OrdN2uZGVHLsRvKbsBdRkIX3BW9sKplch1YTm2CxDLn-sHZ41JdaKiYO1PsFdLNxTdMyiCjlNAbH384ybtVdCi6wSG0D_gWu-uOeX4sqvLwxvmTzjFUpvb4mbaVl_eT3-Z02_CbzLpK8dcCU2RVGhFO3FWSHAONPDTvKBwvxA"}
```
and:

```
{"token_type":"Bearer","expires_in":3600,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImYyNGM3OTM2MzI2OTljZGNiMTRiMWUxYjc1MTc2ZTQyMjA2NzcwNmZmNjRiZWUwMTgwZTRhMGNlOTgwYjZlZjVmMGU3YzM2MzY2NTNjNjNlIn0.eyJhdWQiOiJteWF3ZXNvbWVhcHAiLCJqdGkiOiJmMjRjNzkzNjMyNjk5Y2RjYjE0YjFlMWI3NTE3NmU0MjIwNjc3MDZmZjY0YmVlMDE4MGU0YTBjZTk4MGI2ZWY1ZjBlN2MzNjM2NjUzYzYzZSIsImlhdCI6MTUyMjcwNDgyMSwibmJmIjoxNTIyNzA0ODIxLCJleHAiOjE1MjI3MDg0MjEsInN1YiI6IiIsInNjb3BlcyI6WyJiYXNpYyIsImVtYWlsIl19.PQ9HWbhebohjGrZ_sqfUijiHqTrsBhFLA4A9S5b6FdX2rkv0sP8uqbo7kH9pbDo72qEaYVRW-TGifxQ7BOnWvLvkYEAhIAR8fAgSizCMv3kaDS5pPotWu34_0H9rsbesH2S5Jxl7Fu0TC1Dw_jmLdxvUQHqHUyjNnjEvpwZWSpCZ0xN9KVA_f26l47kfgLqTXbxcINto58A5V658Lv1p92MgbJQ8K5llWPLn9pCvz2gEdJL1iVAurEss76dtx4XTQoI9BJnBHTsa5hH5mc5Jq2YixICMwmWIIBSFz5XPBuDlOVHQIfKB0My_Jr95HbeiMwYUQWKp_CHO0GudvfI9gQ"}
```
The access token is a JWT which is split into three sections, separated by full stops (or periods). The sections are:

* Header
* Payload
* Signature

The header will typically comprise of the hashing algorithm used and other information, which in our case is always the same as can be seen in the examples above.

The body contains the payload of the message so this will differ for each JWT if the contents is different. For each access token generated, we generate a unique ID so that our body will be unique every time.

The final section of a JWT hashes the header and body together to get the signature. You can find more information about JWTs [here](https://jwt.io/introduction/).

As you can see from the examples above, it is only the header that is identical in both scenarios. I hope this clears things up but if you have any further questions, please don't hesitate to get in touch. Again, apologies for the delayed response.

**Comment by jilvin** [comment]
@Sephster Thanks for taking time to resolve this. It was a mistake on my part as I checked the header section alone.

**Comment by Sephster** [comment]
No problem. I suspected that might be the case. Thanks for your patience.
