### ISSUE TITLE
Making tokens shorter? It's almost 1kb..

### ISSUE THREAD

**Issue by juouy** [thephpleague/oauth2-server#807]
Hello,

How can i make issued personal tokens shorter? It's almost 1kb (1000 characters), i want to make mobile app but i can't allow users to waste 1kb on every api request. I know in modern countries people has high data plans, but app is targeted at poorer market... At this moment the token is longer than entire http request i send.

I noticed that private key length has siginificant impact on key length and decreasing it's size to 1024, makes access_token around 500 bytes.

1. Why is token so long?
2. What can be done to reduce it's size?

**Comment by alexbilbie** [comment]
Hi @juouy 

The tokens are long because they are JWT tokens. This allows all the information needed to validate the token and determine the user who owns the token and the permissions granted without requiring a database query. This is really powerful and useful as your service grows.

The best thing you can do is use HTTP 2.0 which automatically compresses HTTP headers and will therefore reduce the amount of data sent between the app and the server significantly. See this blog post for more information - https://blog.cloudflare.com/hpack-the-silent-killer-feature-of-http-2/.

I hope that helps
