### ISSUE TITLE
Differences between access_token and refresh_token

### ISSUE THREAD

**Issue by raulferras** [thephpleague/oauth2-server#809]
I've noticed that encrypted refresh_token contains only hexadecimal characters.
On the other hand, the access_token does not.
This makes the decryption oh both tokens asymmetrical.

I can read in the [RFC](https://tools.ietf.org/html/rfc6749#section-5.1) some examples of the refresh_token and they are not exclusively hexadecimal.

Why is that?

**Comment by mtangoo** [comment]
Refresh Token is a token that you send to get new access token if Oauth2 server supports it. For example if your access token have expired and you have refresh token that is still valid you can use that to get new and valid access token without going thru full grant process (like Auth Code or Password...)

I don't get what you mean about encryption, hex et al so I will skip that for now!

**Comment by simonhamp** [comment]
Thanks for offering an answer @mtangoo.

@raulferras Access Tokens produced by this library are [JSON Web Tokens (JWT)](https://tools.ietf.org/html/rfc7519) and are meant to be able to be unpacked by a token holder so that the token details stored therein can be interpreted. They are **serialised** for safe transport.

Refresh Tokens on the other hand need to be reversibly **encrypted** (in a way that should only be decrypt-able by the token-issuing authority) as they contain sensitive data relevant to the original request that you wouldn't want anyone to be able to forge.

Refresh Tokens are effectively a one-time password that issue a new Access Token using some parameters of the original authentication request without having to complete a full authentication flow.

**Without this encryption, Refresh Tokens would be useless as a security mechanism.**

Generally, you wouldn't be decrypting these anywhere other than in the application/server that generated them.

The method of encryption used determines the format of the encrypted string, hence in this case the refresh tokens produced by this library (by default) are hexadecimal.

**Comment by raulferras** [comment]
Much clearer now, thanks!
