### ISSUE TITLE
AbstractGrant -> validateScopes() method does not support empty scopes anymore

### ISSUE THREAD

**Issue by dorin-niscu** [thephpleague/oauth2-server#829]
Until updating the package everything was fine.
I am using it with Laravel Passport.

Seems that the AbstractGrant -> validateScopes() has been updated so if the scopes array is empty it is not being considered valid anymore.

```
if (empty($validScopes)) {
            throw OAuthServerException::missingScope($redirectUri);
}
```

I added a default scope as a quick fix since it does not let me keep the scopes array empty.

```
Passport::tokensCan([
            'default' => 'Default',
]);
```

**Comment by Sephster** [comment]
Hi @dorin-niscu. Thanks for raising this. The reason this change was made is that the server wasn't  conforming to the RFC spec. If a client issues an auth request with no scope, the server should either:

* Use the default scope specified by the Auth end point
* Issue an invalid scope response if no default is set

Using vanilla OAuth2 server you can just call `setDefaultPassword` but I appreciate that Passport doesn't have an equivalent at the moment.

I will need to think this over but will get back to you soon with a path forwards. Apologies for any inconvenience caused.

**Comment by Sephster** [comment]
@dorin-niscu I've temporarily removed the check on empty scopes. Can you upgrade to version 6.1.1 and confirm if this has resolved your problem? Thanks

**Comment by dorin-niscu** [comment]
@Sephster Seems to be fine. Thanks.
I did not check the code in depth but is not possible to add a default scope and keep the validation backwards compatible ?

**Comment by Sephster** [comment]
Long term we need to change the server so that if an auth token request is issued without a scope, and you have not specified a default scope, the server should be responding with an invalid token response as defined in the OAuth spec.

The package provided a `setDefaultScope` method to allow you to set a default scope for use in this instance. The problem is that there isn't an equivalent function in Passport at the moment so to save problems for people, I removed the check. I will need to discuss with other maintainers the best route forwards to get this change back in place without causing issues for Passport users.

**Comment by Sephster** [comment]
Going to mark this issue as closed now as version 6.1.1 has resolved you problem. Thanks for reporting it to us and apologies again for any inconvenience caused.

**Comment by alexbilbie** [comment]
@sephster my understanding of 3.3 of the spec is that if the request contains no scopes and there are no scopes defined on the default scopes array then the request would be valid still

**Comment by Sephster** [comment]
Hi @alexbilbie. It is the last section of 3.3 that makes me believe we must have a scope present although, I admit, it could be worded more clearly:

> If the client omits the scope parameter when requesting
   authorization, the authorization server MUST either process the
   request using a pre-defined default value or fail the request
   indicating an invalid scope.  The authorization server SHOULD
   document its scope requirements and default value (if defined).

Because of the word _must_ in there, I believe we have to fall back to using a default scope in most instances. If it isn't set, we have no option but to issue a failure.

**Comment by alexbilbie** [comment]
Access tokens are for more than just authorisation in my opinion, they can represent a verified identity too - this is the case for our JWT tokens which embed the user's ID in the `sub` claim.

IMO if there are no scopes in the request, and the default scope on the auth server is no scope then this is valid.

**Comment by Sephster** [comment]
OK I see. I had assumed a scope must always be some string and hadn't thought of the scenario where a default blank string could in itself be considered a default state. With you now!

Main thing I am wondering now is in what scenario would we issue an invalid scope as per the rfc? I presume this would be if the default scope was set to null. Is this worth implementing? I can't see many people wanting to do this to be honest but would welcome some guidance
