### ISSUE TITLE
A fix to support for multiple client redirect URI

### ISSUE THREAD

**Issue by yombo** [thephpleague/oauth2-server#834]
I found issue #168 that mentions supporting multiple redirect uris, however, there was no fix posted.

If found that if i change line one line, everything seems to work to support multiple redirect uri's, including validation.

https://github.com/thephpleague/oauth2-server/blob/57ca83a8baadd5b5a6c1d82da7d261089e55585c/src/Grant/AuthCodeGrant.php#L243

**Before:**
```
        } elseif (is_array($client->getRedirectUri()) && count($client->getRedirectUri()) !== 1
```

**After:**
```
        } elseif (is_array($client->getRedirectUri()) && count($client->getRedirectUri()) === 0
```

I tried to Google-fu this, and perhaps I missed a previous discussion. But why create an array using a comma separated list and then only allow one redirect URI?

**Comment by Sephster** [comment]
I believe this is working as intended. If you have registered multiple redirect uris, you must pass a redirect_uri with your auth request so that the server knows which of the multiple redirect uris to use for the given request as shown in the code below:

```
$redirectUri = $this->getQueryStringParameter('redirect_uri', $request);
        if ($redirectUri !== null) {
            if (
                is_string($client->getRedirectUri())
                && (strcmp($client->getRedirectUri(), $redirectUri) !== 0)
            ) {
                $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
                throw OAuthServerException::invalidClient();
            } elseif (
                is_array($client->getRedirectUri())
                && in_array($redirectUri, $client->getRedirectUri()) === false
            ) {
                $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
                throw OAuthServerException::invalidClient();
            }
        }
```

If you have only registered one redirect_uri against the client, there is no ambiguity so you can omit the redirect_uri from the auth request and the server will use the pre-registered redirect uri.

The `count($client->getRedirectUri()) !== 1)` check ensures that if you have more than one redirect_uri registered, you must specify which one you want to use for your auth request.

I hope that I've explained this properly but if you have any further questions or comments please let me know. Cheers.
