### ISSUE TITLE
unsupported_grant_type when client_id is missing

### ISSUE THREAD

**Issue by Jimbolino** [thephpleague/oauth2-server#837]
http://localhost/oauth/authorize?client_id=1&response_type=code
`{"error":"invalid_client","message":"Client` authentication failed"}`

http://localhost/oauth/authorize?response_type=code
`{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}`

I would expect that OAuthServerException::invalidRequest('client_id'); would thrown, but because none of the grants canRespondToAuthorizationRequest() this check is never done. And the code continues to throw a OAuthServerException::unsupportedGrantType()

There is a check in validateAuthorizationRequest: (is_null($clientId)), but this code can never be reached because of canRespondToAuthorizationRequest()

Its not really a bug, but the "Check the `grant_type` parameter" message was pointing me the wrong way.

**Comment by Sephster** [comment]
Thanks for reporting this @Jimbolino -  I will try and look into this shortly

**Comment by alexbilbie** [comment]
So the actual fail point is when the [`canRespondToAuthorizationRequest`](https://github.com/thephpleague/oauth2-server/blob/master/src/Grant/AuthCodeGrant.php#L193-L200) method is checked on the  auth code grant.

Presently this requires both the `response_type` query parameter to equal `code` and the `client_id` parameter to be present.

This line of code was written almost two years ago and I can't remember why I added the `client_id` parameter check. It might be overly strict but then it might be because the OAuth spec requires the `client_id` property for this grant type to be valid.

**Comment by simonhamp** [comment]
I've definitely hit this before and it's definitely been trickier than it needs to be to track down. The commit above fixes this case of it, but I haven't checked for others yet.

Would appreciate you giving this a test @Jimbolino if/when you get chance.

**Comment by Sephster** [comment]
This issue will also affect the Implicit Grant. I think the problem here is that we are performing some of the validation inside the `canRespondToAuthorizationRequest()` function.

It would be better to just return `true` for the grants that can respond to authorization requests to allow the flow to continue to the `validateAuthorizationRequest()` function and place all actual validation inside there.

This will mean an interface change as we will no longer need the request object for the `canRespondToAuthorizationRequest()` function so will need to be done as part of a major release at some point.

Re-opening for the timebeing as the issue will need to be rectified for the Implicit Grant as well. Long term, it would be good to implement the changes outlined above and remove validation from the `canRespondToAuthorizationRequest()` function completely.

**Comment by Sephster** [comment]
Sorry, I hadn't noticed that the implicit grant and auth code grant are differentiated in their check by the response type, hence the need for the request being passed in at that point. Will require some further thought

**Comment by simonhamp** [comment]
@Sephster I don't think it matters too much because both of these methods get called inside `[AuthorizationServer::validateAuthorizationRequest()](https://github.com/thephpleague/oauth2-server/blob/7.0.0/src/AuthorizationServer.php#L143-L152)`, so validation is the goal one way or another.

If someone happens to use either of the Grant methods separately in their implementation, I feel that having the validation happen in both becomes necessary to maintain compliance with the spec.

So centralising the `client_id` parameter check - even down into the `AbstractGrant` - may be the best way of handling it overall.

**Comment by Sephster** [comment]
I've had a big think about this and I actually think the initial functionality was correct. Although the error messages at first appear confusing, they are actually valid and appropriate given the circumstances.

Unlike the request for an access token, we don't specify the grant type when requesting auth tokens. The two grants that can validate authorization requests are the _implicit_ grant and the _auth code_ grant.

Both __require__ a response type to be specified and a client ID according to the spec. The response type is the only differentiating factor here and it is how we route to an appropriate grant e.g. _code_ for the _auth code_ grant and _token_ for the _implicit_ grant.

If you are omitting the client ID from a request, this is not a valid call to either the implicit grant or the auth code grant. If the library responds with an _invalid client_ response, we are assuming you meant to call either of these grants but we cannot make that assumption as there is not enough information to go on.

A developer might have implemented a custom grant which can also validate authorization requests but doesn't require the same set of parameters for example. 

Because it is a requirement to provide the client ID to these grants, it is a calling issue rather than a library issue when you do not. We cannot make assumptions about what you intended in this instance.

I think that the hint for the exception probably needs to be updated as you never pass a *grant_type* for an auth request but other than that I don't think there is much else to be done. I am going to revert the fix so I can release some of the unreleased features. Sorry it has taken so long to investigate this
