### ISSUE TITLE
RefreshTokenEntityInterface:getAccessToken appears to be unused + Question

### ISSUE THREAD

**Issue by michaeldnelson** [thephpleague/oauth2-server#855]
I really have enjoyed working with this package.  

It appears to me that this RefreshTokenEntityInterface:getAccessToken is not used by the project and as such does not need to be implemented.  

BearerTokenResponse is passed the AccessTokenEntityInterface and injects all the access token information required to issue new access tokens into the encrypted response_token.  As such RefreshTokenEntityInterface:setAccessToken, though currently used in AbstractGrant, may also be unnecessary.

As a related issue, I was considering not storing access tokens (or revoked access tokens) at all and relying on a short timeout.  This would require me adding these as implementations to the AccessTokenRepository.  Refresh tokens would be revokable considering their longer lifespan.

    public function revokeAccessToken($tokenId)
    {
        //short lived tokens;
        return null;
    }

    public function isAccessTokenRevoked($tokenId)
    {
        //short lived tokens
        return false;
    }

I think this would considerably reduce the load on my db but I am not sure if I am seriously compromising security.  Any feedback would be welcome.  Thanks!

edit: added more detail regarding response_token.

**Comment by Sephster** [comment]
Hi @michaeldnelson. That's great to hear that you're finding the package useful. Thanks for supporting it.

The source files themselves don't use the `getAccessToken` method directly as you've stated. The reason we have access tokens at all in the refresh entity is because the server will issue a refresh token when it sends  an access token so bundling the two together in a single entity seems the logical way to go. We have a `setAccessToken()` method to store the access token in the entity and have a complimentary `getAccessToken()` method should the implementer need this for any reason.

We use this method in our tests for example, to easily verify that when a grant responds to an access token request, it has set the access token correctly.

I would be hesitant to remove this function as other implementers might be relying on it for their own tests/use cases which I'm not aware of. It isn't adding any overhead to the base running of the system but does allow the code to be more extensible. I hope you understand but if you have any more questions feel free to ask about this.

I'm not entirely sure how your scenario would work. When you issue the access token, you would need to store it in the DB so you can later validate against it, even if it is only used one time. You could set a very short lifespan for the access token as you mentioned but I can't think of a way to not store the access token within the confines of the OAuth spec. 

I would imagine you would actually increase the load on your DB slightly if you went down the route of having very short lived access tokens as you would have a lot more writes to your database whenever you need a new one. You would also need to go through the authentication process a lot more. Apologies if I've misunderstood the scenario you outlined but I hope this has been of some assistance.

**Comment by michaeldnelson** [comment]
*I'm not entirely sure how your scenario would work. When you issue the
access token, you would need to store it in the DB so you can later
validate against it, even if it is only used one time. You could set a very
short lifespan for the access token as you mentioned but I can't think of a
way to not store the access token within the confines of the OAuth spec.*

It is my understanding that a signed jwt is self contained and its validity
for use can be determined by verifying that you are the signer, it does not
require the verification of a database lookup.

**Comment by michaeldnelson** [comment]
Hi @Sephster 

Here is an article detailing the use of JWS to sign access tokens to reduce db 

https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/

Here is a relevant except:

_Whether tokens are opaque or not is usually defined by the implementation. Common implementations allow for direct authorization checks against an access token. That is, when an access token is passed to a server managing a resource, the server can read the information contained in the token and decide itself whether the user is authorized or not (no checks against an authorization server are needed). This is one of the reasons tokens must be signed (using JWS, for instance). On the other hand, refresh tokens usually require a check against the authorization server._

**Comment by Sephster** [comment]
Sorry, my original comment was incorrect. I should really check these things before responding so thank you both for correcting me.

Because the package use JWT as you noted, no DB call is required to check the validity of an access token. However, as you also noted, we do need some way of checking if a token has been revoked which cannot be achieved from the JWT alone.

In your scenario, even though you have short lived access tokens, I would not recommend removing the ability to revoke these tokens by not tracking them in some way. Although the period that your server could be compromised would be short lived, it would still  be a security concern to have no way of preventing the compromised access token from being used short of changing the code or turning off complete access to the server.

If you are concerned about the overhead of checking if the access token is revoked, I would recommend looking at differing storage solutions to arrive on one which minimises the overhead for you but still provides an adequate level of security to not be compromised. As @mtangoo noted, we do not make any assumptions about what storage you use so you are free to make this choice.

**Comment by michaeldnelson** [comment]
Thank you for your responses. I have some thoughts about possible scenarios but it seems like a lot of this is still very fuzzy especially around securing single page apps :) Regardless, as I said, I appreciate this library.  It provides a lot of functionality while not forcing an implementation.
