### ISSUE TITLE
How to handle user login (and not oauth clients)?

### ISSUE THREAD

**Issue by nealoke** [thephpleague/oauth2-server#879]
I've implemented the `oauth2-server` which is awesome (but sometimes unclear) library :smile: . The problem is however, separate from oauth clients I also have users who just need to login. Do they do this with another grant then the `authorization_code`? If so which one? 

Currently I'm doing this via my one-page application via a http POST request with username and password.

**Comment by nealoke** [comment]
Thanks for the quick follow up :+1: 

But I'm afraid I don't fully understand what I should do now. The thing is currently my `oauth clients` can have access to my `resource server` (aka my api). But because I'm using the `ResourceServerMiddleware` it errors when my front-end application tries to access the api on behalf of the user that is logged in due to the missing JWT token. 

If I understand correctly I should create an `oauth client` for my  front-end application and on my `resource server` use the `ResourceServerMiddleware` to get to the `oauth_user_id` and `oauth_client_id`. From there check if the `oauth_client_id` matches the one from the front-end application?

Would it be wise to create a helper class on my `resource server` which stores this information like 
```
class user {
    protected $userScopes; // Array of scopes
    protected $userAccounts; // Array of accounts

    public function setAccess($userId) {
        // Set $userScopes based on $userId
        // Set $userAccounts based on $userId
    }

    public function canAccessScope($scope) {
        // True or false
    }
    
    public function canAccessAccount($accountId) {
        // True or false
    }
}
```

Any idea on how to make this available to all routes in a slim framework? :)

**Comment by nealoke** [comment]
I receive the following error message:
`{"error":"access_denied","message":"The resource owner or authorization server denied the request.","hint":"Missing \"Authorization\" header"}`

**A small recap on the situation**
So out of your answer and my stackoverflow question it becomes clear that the OAuth flow is not for typical user logins. I would like to create an endpoint on my auth server for logins such as `myauth.com/login`. This endpoint will accept a HTTP POST request containing the credentials of the user. For this to work I would need to validate the user (ok) and then create a `JWT token` for the user. 

My question, how can I create this token on my `myauth.com/login` endpoint with the `oauth-server` package?

**Comment by simonhamp** [comment]
IMHO, you're better off sticking to your standard auth methods for users logging directly into your service. The extra step of giving those users an OAuth token will give you unnecessary headaches and add a redundant layer of complexity to your code.

Remember, OAuth is ideally suited to stateless APIs, especially ones that you want to allow third-party clients to have access to your users' data on their behalf, which would otherwise require the third-party client to store and transmit your users' usernames and passwords.

Your application is likely neither of these things. It sounds like it's a stateful web app, e.g. you have server-side user sessions that rely on a cookie on the client to identify them in your application. And it's definitely a first-party client that you control, so your trust level around credential storage and transmission should be pretty high.

So to get around the middleware issue, you should consider separating your stateful web routes from your stateless API routes. That way you can apply your `ResourceServerMiddleware` only to the API routes, whilst your web routes allow access only via an authenticated session.

**Comment by Sephster** [comment]
Yeah, @simonhamp is right. You should have a user login that is not relying on OAuth 2. OAuth 2 is for protecting your API, not the login to your application itself.

**Comment by Sephster** [comment]
@nealoke I'm going to close this issue as there hasn't been any activity in over a week. If you still have questions please feel free to comment and we will reopen it for further discussion
