### ISSUE TITLE
Why isn't auth code grant validate the client secret?

### ISSUE THREAD

**Issue by starx** [thephpleague/oauth2-server#881]
Hi, 

I was wondering why client secret is not used to verify the client?

And this part is actually part of the core grant class, not the example implementation.

https://github.com/thephpleague/oauth2-server/blob/9fc288ce53bbd198ceb7be604ca00dc3910a7d82/src/Grant/AuthCodeGrant.php#L247

**Comment by Sephster** [comment]
The auth code grant is typically used by third party clients and web apps such as SPA's that cannot usually keep confidential information secret. Because of this, the server does not expect the client to transfer their client secret if they are using the auth code grant, and does not expect the client to be trusted, so will not validate their client credentials.

Instead, we do a basic check ensuring that the registered redirect uri(s) sent, match with what was originally registered. Please check the RFC [section 2.3](https://tools.ietf.org/html/rfc6749#section-2.3) for more information. 

I hope this answers your question, but if not, please shout.

**Comment by starx** [comment]
@Sephster Makes sense. Thanks
