### ISSUE TITLE
laravel/passport@4.0.x responds with "Object of class DateTime could not be converted to string"

### ISSUE THREAD

**Issue by hgs81** [thephpleague/oauth2-server#883]
Using laravel passport Password Grant, the following code line fails and responds to client with this string: "Object of class DateTime could not be converted to string".
https://github.com/thephpleague/oauth2-server/blob/9fc288ce53bbd198ceb7be604ca00dc3910a7d82/src/Grant/AbstractGrant.php#L372
My request was POST http://localhost/oauth/token with proper required parameters.
Please let me know how to fix it asap.

**Comment by Sephster** [comment]
@hgs81 I'm closing this as I haven't heard back from you. This issue is probably better dealt with in Passport as it is dealing with a Passport implementation and I see you have [opened an issue](https://github.com/laravel/passport/issues/688) in that repository as well.

At first glance I suspect this is something to do with the conversion of the expiryDate from a DateTime object to a string but couldn't say for certain without seeing more of your implementation. I hope it is sorted for you soon and sorry I can't assist any further. If you do provide more information I will be happy to take another look at this. Cheers

**Comment by hgs81** [comment]
Thanks, @Sephster.
I also don't think this is not an issue about this repository.
But I cannot find implementation of persistNewAccessToken() method in laravel/passport.
Also I tested with raw php when this error occurs.
This code raised same error:
```php
echo (new DateTime());
```
$accessToken var dump contains DateTime type variable 'expiryDate'.
Perhaps is this version problem? I want to know if old version of AccessToken implementation has string type 'expiryDate'.

PS: 
There is live backend online that works with same code.
I wanted to test it locally so I cloned all source code, compose install, and launch.
But I met this error.
Backend is maintained by another ops engineer.
Just yesterday, he said he updated backend with latest push.
And after that, live backend also occur same error.
If you can tell me most stable version of oauth2-server and laravel/passport version, I would be thank you.

**Comment by Sephster** [comment]
The latest versions of both libraries should be stable. For OAuth 2 Server it is version 7.1.0 and for Passport it is version 6.0.0
