### ISSUE TITLE
Dedicated Private/Public Keys per client

### ISSUE THREAD

**Issue by mtangoo** [thephpleague/oauth2-server#894]
Am sharpening my Oauth2 design skills and have faced a little problem. I have been using same priv/Pub keys set for all clients and now I want to separate them, each to use its own.

Now I find current design is so hard to accomplish that (May be because I miss something). I have one place that I create server instance and store it in the DI container and pull that instance everywhere else.  I can only define keys here. This IMHO is not consistence with the rest of the library where it asks for something at the point when it needs it via interface.

Why is there no interface/abstract method in the grant for picking the key when needed? With current status what is the advice for multiple keys?

Sorry if I missed something basic.
Cheers!

**Comment by Sephster** [comment]
The library hasn't really been designed to use multiple encryption keys. In general, it is very unlikely that your keys will ever be compromised because, as long as you are following modern practices, it is nigh on impossible to break them.

We are taking the stance that if you keep your key secure, you shouldn't have a need for multiple keys. Realistically the only way that your keys could become compromised is if someone gains access to your server and if this happens, all keys on the server will be compromised anyways and need to be replaced. 

If you have any literature indicating that it is good practice to use multiple keys for different clients then please do share it but I don't believe this is something we would cater for at this point as there isn't a clear benefit and it makes the library more complicated.

**Comment by mtangoo** [comment]
I see you have a point. Since I can't fault your arguments, I'll close this one. 

Thanks for clearing out my double
