### ISSUE TITLE
Use scope to a specific subset of resources

### ISSUE THREAD

**Issue by jacksun101** [thephpleague/oauth2-server#936]
Let's say, I am developing an oauth2 server for smart home hubs. I would like to create couple scopes as below.

hubs:query:*
hubs:control:*

And when user is asked for approval, he/she can select hub. I think maybe it makes sense to store in the access token (or session) scope like below.

hubs:query:1        ( Just hub 1 )
hubs:control:1|2    ( hub 1 & 2 )

Is this making any sense? Or any better idea for the client to access a subset of resources that user granted?

**Comment by mtangoo** [comment]
Am not sure I understand your problem. But the library gives you power to do anything you want.
Did you face a specific problem?

**Comment by Sephster** [comment]
The client would typically decide what scopes are required, rather than the user. The user will just provide authorisation to the client for the specified scopes. If the client does not require access to hub 2 for example, it shouldn't request access to hub 2. I hope that makes sense.

**Comment by sg3s** [comment]
The dilemma is that sometimes you want users to be able to grant clients access to specific entity IDs in a resource server which are not known to the client beforehand. A selection step is presented to the user when reviewing the client authorisation request. 

Sort of how some central Git repositories (dunno if Github can do this) can let you share specific git repositories with 3rd party services, instead of blanket access to all repositories in an account.

@jacksun101 I believe this is already possible by utilizing the `ScopeRepository->finalizeScopes()` function which you must implement as part of the `ScopeRepositoryInterface`.
https://oauth2.thephpleague.com/scope-repository-interface/

1. Let the client request the scopes as you defined. 
2. Feed the interface the selectable data for the user using the wildcard scopes. 
3. Do a (pre-oauth2-server) check for the input given by the user. 
4. Use the input given by the user during the `->finalizeScopes()` to replace the wildcard scopes with the appropriate scopes and actual IDs embedded in them.

**Comment by Sephster** [comment]
Closing this due to no response from @jacksun101.
