### ISSUE TITLE
Examples folder is not included in the .zip file!

### ISSUE THREAD

**Issue by rapgithub** [thephpleague/oauth2-server#939]
Examples folder is not included in the .zip file! please verify I need to install the OAuth2ServerExamples thanks

**Comment by Sephster** [comment]
Hi @rapgithub - the examples directory is not included as zip file download is supposed to be used as a drop in replacement for the composer install option so that you can just extract the folder and prepare it for production. In production you won't require the examples or tests folder so these haven't been included.

If you want to download the examples directory you can clone the repository in git which will include the files. Hope this helps!
