### ISSUE TITLE
BearerTokenValidator::validateAuthorization() - jti and scope(s) 

### ISSUE THREAD

**Issue by pjdevries** [thephpleague/oauth2-server#943]
Hi,

I'm not quite as theoretically educated as most here and rather new to OAuth2 in general and this interesting implementation in specific. I do run into a few issues in `BearerTokenValidator::validateAuthorization()` though:

First of all the token revoked check. It executes `$token->getClaim('jti')`, without a second default parameter. This results in an exception being thrown whenver the JWT does not contain a 'jti' claim. From what I read in [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.5), 'jti' is optional, so its absence should not result in an exception. I think this can be solved by passing an empty string as the second parameter to `$token->getClaim('jti')`. In fact the same goes for all other `$token->getClaim()` calls checking optional claims.

Secondly there is the return value:
```
return $request
                ->withAttribute('oauth_access_token_id', $token->getClaim('jti'))
                ->withAttribute('oauth_client_id', $token->getClaim('aud', ''))
                ->withAttribute('oauth_user_id', $token->getClaim('sub', ''))
                ->withAttribute('oauth_scopes', $token->getClaim('scopes'));
```
The first point I made also goes for these claims, since they are all optional. Apart from that, I had some issues with the `scopes` claim when testing the `ResourceServer` with an auth0.com account. Apparently they use `scope` without the trailing 's'. I realize scope(s) is not a registered claim name. However, some searching seems to indicate that `scope` is used more often than `scopes`. My suggestion would be to check for both.

Just my two cents :)

**Comment by Sephster** [comment]
Hi @pjdevries. Thank you for your comments. You are right in saying that the JTI is not a required claim but our server uses it to set the ID of the token. Because our server is the one issuing the access token, we should be confident that this value will be populated when checking any access tokens. 

Similarly, we don't bother to check the claims unless the JWT has first been validated to ensure it hasn't been tampered with so there shouldn't be a scenario where we need to set a value to avoid an exception being thrown.

I take your point on the scopes vs scope but we would be hesitant to change this as it would break backwards compatibility and as this is a custom claim and the tokens issues by our server package will only be used by our server package, I don't think it is too big a concern.

I hope this clears up some of our decisions. If you do have any further comments please don't hesitate to get in touch. Thanks for reaching out.
