### ISSUE TITLE
can i user this extension in yii2?

### ISSUE THREAD

**Issue by uiisoft** [thephpleague/oauth2-server#979]
i am a beginner,i I'm using yii2.Can I use this extension in yii2?If so, can you give me some guidance?

**Comment by mtangoo** [comment]
Yes, we have implemented it in our projects with no problem. You have to start with documentation of different interfaces (assuming you already know Oauth2)

**Comment by Sephster** [comment]
@uiisoft I'm afraid I don't know of any out of the box installations for yii2 so I imagine you will need to roll your own. To find out more about how to do this, I would advise checking the [documentation on our website](https://oauth2.thephpleague.com/) and also refer to the [examples](https://github.com/thephpleague/oauth2-server/tree/master/examples) which are implemented in the Slim Framework.

The library is designed to be flexible so it doesn't require any specific framework or even a specific database backend. We provide a set of interfaces which can effectively be seen as wrappers or contracts for the data the library requires.

As this isn't a specific issue about the package I am going to mark this as closed as I feel this issue is too broad to effectively deal with here. If you do require further assistance once you have reviewed the documentation feel free to reach out to me via email.

Cheers and good luck!
