### ISSUE TITLE
Incorrect Docblock Param Type in Entity

### ISSUE THREAD

**Issue by Sephster** [thephpleague/oauth2-server#986]
There appears to be a discrepancy in docblocks for the ClientEntityInterface. The interface says that the `getIdentifier` function will return a string.

However, in the EntityTrait which can be used to implement the ClientEntityInterface, the `$identifier` is declared as a string but the _set_ and _get_ functions accept _mixed_ values. 

I think the identifier probably should be mixed rather than a string as it should be up to the implementer what the identifier is. This issue was identified by @driesvints in this Passport issue https://github.com/laravel/passport/issues/581

**Comment by crtl** [comment]
Some people use object ids as their identifiers so in my opinion this behaviour is desired.
`getIdentifier` is called by the library which expects a string but due to the missing type hint the implementation can vary and we can use whatever identifier types we want to use.
We just have to return a `string` for `getIdentifier`.

**Comment by Sephster** [comment]
That's a good point. Thanks for looking at this @crtl. I will close this issue down as your logic makes sense.

WRT to the traits vs interfaces comment, I'm sorry if I was not clear enough on this point but I did not confuse these terms.
