### ISSUE TITLE
Version 8

### ISSUE THREAD

**Issue by darrencoutts118** [thephpleague/oauth2-server#992]
Hi Guys, 

It looks like you have a lot of good things planned for version 8 - which is fantastic! Do you have any idea when it is likely to be released? 

I also note that there is no development branches to see how things are progressing, and to take a look how we may integrate - am I missing something?

**Comment by darrencoutts118** [comment]
cc/ @Sephster

**Comment by Sephster** [comment]
I had originally said the end of January but I didn't get as much time to work on this over the Christmas period as I would have liked. I'm hesitant to offer any further estimation as this is likely to be wrong.

Anything that is due to go into version 8 and has been completed is in the version 8 branch. We don't have development branches as have no real need for them. Development will largely be done on a contributors fork until they are ready to submit a PR. 

Cheers!
